package com.mkarasz.hw5.playTone;

import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;

/**
 * 
 * Simple playback of linear pcm data.
 * 
 * Data for playback is generated by the Note class
 * 
 * todo: modify the note.setNote() line to suit your needs
 * 
 */
public class Tone {

	public static void main(String[] args) throws LineUnavailableException {

		MIDI midi = new MIDI(41, NoteValue.HALF);
		Tempo tempo = new Tempo(120, NoteValue.HALF);
		
		Note note = new Note(16);

		//Linear PCM data to be created with byte array from note.setNote()
		final AudioFormat format = new AudioFormat(note.getSampleRate(), 8, 1, true, true);

		//open up a line with audio format
		SourceDataLine line = AudioSystem.getSourceDataLine(format);

		//get info about line
		DataLine.Info info = new DataLine.Info(SourceDataLine.class, format); // format is an AudioFormat object
		//debug
		System.out.println(info.toString());

		if (!AudioSystem.isLineSupported(info)) {
			//handle the error
			return;
		}
		// Obtain and open the line.
		try {
			line = (SourceDataLine) AudioSystem.getLine(info);
			line.open(format);

			for(int i = 45; i < 90; i++) {
				//todo: parameters to setNote should be a MIDI and a Tempo object
				midi.setMidiNumber(i);
				note.setNote(midi, tempo);
				//System.out.println("" + i);
				//note.setNote(i, .25);
				//longer note duration
				//note.setNote(i, 1);

				//no need to modify these lines   
				line.start();
				line.write(note.getNote(), 0, note.getLength());
			}
			line.drain();
			line.close();
		} catch (LineUnavailableException ex) {
			// Handle the error.
			ex.printStackTrace();
		}

	}
}
